CREATE TABLE IF NOT EXISTS tasks (
                                     id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                     title VARCHAR(50) NOT NULL,
    description VARCHAR(255),
    status VARCHAR(25) NOT NULL,
    priority VARCHAR(30),
    created_on TIMESTAMP NOT NULL,
    due_date TIMESTAMP
    );