CREATE TABLE IF NOT EXISTS users (
                                     id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                     first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50),
    email VARCHAR(50) NOT NULL,
    password VARCHAR,
    role VARCHAR(10),
    gender VARCHAR(10) NOT NULL,
    access_token VARCHAR(1000),
    UNIQUE(email)
    );